enum EscrowStatus {
  PENDING = 'PENDING',
  FUNDED = 'FUNDED',
  COMPLETED_PENDING_PAYOUT = 'COMPLETED_PENDING_PAYOUT',
  RELEASING = 'RELEASING',
  RELEASED = 'RELEASED',
  REFUNDING = 'REFUNDING',
  REFUNDED = 'REFUNDED',
  DISPUTED = 'DISPUTED',
}

export { EscrowStatus };
