enum EscrowStatus {
  PENDING = 'PENDING',
  FUNDED = 'FUNDED',
  HELD = 'HELD',
  RELEASING = 'RELEASING',
  RELEASED = 'RELEASED',
  REFUNDING = 'REFUNDING',
  REFUNDED = 'REFUNDED',
  DISPUTED = 'DISPUTED',
}

export { EscrowStatus };
