enum LedgerEntryType {
  ACTIVE_ERRAND_CREDIT = 'ACTIVE_ERRAND_CREDIT',
  ACTIVE_ERRAND_REVERSAL = 'ACTIVE_ERRAND_REVERSAL',
  PENDING_CREDIT = 'PENDING_CREDIT',
  PENDING_REVERSAL = 'PENDING_REVERSAL',
  AVAILABLE_CREDIT = 'AVAILABLE_CREDIT',
  WITHDRAWAL_DEBIT = 'WITHDRAWAL_DEBIT',
  REFUND_CREDIT = 'REFUND_CREDIT',
}

export { LedgerEntryType };
