import { Twilio } from 'twilio';

const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;
const twilioWhatsAppNumber = process.env.TWILIO_WHATSAPP_NUMBER;
const twilioSmsNumber = process.env.TWILIO_SMS_NUMBER;
const contentSid = process.env.TWILIO_OTP_CONTENT_SID;

const client = new Twilio(accountSid, authToken, {
  logLevel: 'debug',
  autoRetry: true,
  maxRetries: 2,
});

/**
 * Send OTP via WhatsApp using Twilio
 * @param phoneNumber - The recipient's phone number (with country code, e.g., +2348167310747)
 * @param otp - The OTP code to send
 */
const sendWhatsAppOTP = async (phoneNumber: string, otp: string) => {
  const message = await client.messages.create({
    from: twilioWhatsAppNumber,
    contentSid: contentSid,
    contentVariables: JSON.stringify({ '1': otp }),
    to: `whatsapp:${phoneNumber}`,
  });

  console.log('WhatsApp OTP sent successfully. Message SID:', message.sid);
  return message;
};

/**
 * Send OTP via SMS using Twilio
 * @param phoneNumber - The recipient's phone number (with country code, e.g., +2348167310747)
 * @param otp - The OTP code to send
 */
const sendSmsOTP = async (phoneNumber: string, otp: string) => {
  const message = await client.messages.create({
    body: `Your Errandy verification code is: ${otp}. This code expires in 10 minutes.`,
    from: twilioSmsNumber,
    to: phoneNumber,
  });

  console.log('SMS OTP sent successfully. Message SID:', message.sid);
  return message;
};

/**
 * Send OTP - tries WhatsApp first, falls back to SMS if WhatsApp fails
 * @param phoneNumber - The recipient's phone number (with country code, e.g., +2348167310747)
 * @param otp - The OTP code to send (generated by better-auth)
 */
export const sendOTP = async (phoneNumber: string, otp: string) => {
  try {
    // WhatsApp OTP Disabled for now
    /*
    // First, try to send via WhatsApp
    console.log('Attempting to send OTP via WhatsApp to:', phoneNumber);
    const result = await sendWhatsAppOTP(phoneNumber, otp);
    return { channel: 'whatsapp', ...result };
    */

    // Default to SMS
    console.log('Attempting to send OTP via SMS to:', phoneNumber);
    const result = await sendSmsOTP(phoneNumber, otp);
    return { channel: 'sms', ...result };
  } catch (error) {
    console.error('SMS OTP failed:', error);
    throw new Error('Failed to send OTP via SMS');
  }
};
